# Generated by Django 6.0 on 2025-12-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-published_at', '-is_breaking', '-is_featured']},
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='is_breaking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='reading_time',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='seo_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='seo_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
