# Generated by Django 6.0 on 2025-12-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsarticle_options_newsarticle_is_breaking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('published', 'Published')], default='draft', max_length=20),
        ),
    ]
